import { describe, it, expect } from "vitest";
import { createPairingPayload } from "../../auth/pairing.js";

/**
 * Cross-package validation: verifies the QR data format generated by
 * the MCP server matches what the mobile app's parseQRData() expects.
 *
 * The mobile app's parseQRData() expects these fields (all strings):
 *   - pairingId
 *   - relayUrl
 *   - deviceName
 *   - deviceId
 *   - publicKey
 *   - encryptionPublicKey
 *
 * The MCP server generates: createPairingPayload() + { pairingId } spread.
 */

/** Mirrors mobile app's parseQRData validation logic exactly. */
function mobileParseQRData(
  raw: string
): {
  pairingId: string;
  relayUrl: string;
  deviceName: string;
  deviceId: string;
  publicKey: string;
  encryptionPublicKey: string;
} | null {
  try {
    const data = JSON.parse(raw);
    if (
      typeof data.pairingId === "string" &&
      typeof data.relayUrl === "string" &&
      typeof data.deviceName === "string" &&
      typeof data.deviceId === "string" &&
      typeof data.publicKey === "string" &&
      typeof data.encryptionPublicKey === "string"
    ) {
      return {
        pairingId: data.pairingId,
        relayUrl: data.relayUrl,
        deviceName: data.deviceName,
        deviceId: data.deviceId,
        publicKey: data.publicKey,
        encryptionPublicKey: data.encryptionPublicKey,
      };
    }
    return null;
  } catch {
    return null;
  }
}

describe("QR format compatibility: MCP server → mobile", () => {
  const testDeviceId = "device-abc-123";
  const testPublicKey = "dGVzdC1wdWJsaWMta2V5LWJhc2U2NA==";
  const testEncryptionPublicKey = "dGVzdC1lbmMtcHVibGljLWtleQ==";
  const testRelayUrl = "https://relay.punchdown.dev";
  const testDeviceName = "Daves-MacBook-Pro.local";
  const testPairingId = "pair-xyz-789";

  it("createPairingPayload + pairingId produces valid QR data for mobile", () => {
    const payload = createPairingPayload(
      testDeviceId,
      testPublicKey,
      testEncryptionPublicKey,
      testRelayUrl,
      testDeviceName
    );

    // CLI spreads payload and adds pairingId (see cli.ts line 94)
    const qrData = { ...payload, pairingId: testPairingId };
    const serialized = JSON.stringify(qrData);

    const parsed = mobileParseQRData(serialized);
    expect(parsed).not.toBeNull();
    expect(parsed!.pairingId).toBe(testPairingId);
    expect(parsed!.relayUrl).toBe(testRelayUrl);
    expect(parsed!.deviceName).toBe(testDeviceName);
    expect(parsed!.deviceId).toBe(testDeviceId);
    expect(parsed!.publicKey).toBe(testPublicKey);
    expect(parsed!.encryptionPublicKey).toBe(testEncryptionPublicKey);
  });

  it("all required fields are present after createPairingPayload + pairingId", () => {
    const payload = createPairingPayload(
      testDeviceId,
      testPublicKey,
      testEncryptionPublicKey,
      testRelayUrl,
      testDeviceName
    );
    const qrData = { ...payload, pairingId: testPairingId };

    const requiredFields = [
      "pairingId",
      "relayUrl",
      "deviceName",
      "deviceId",
      "publicKey",
      "encryptionPublicKey",
    ];

    for (const field of requiredFields) {
      expect(qrData).toHaveProperty(field);
      expect(typeof (qrData as Record<string, unknown>)[field]).toBe("string");
    }
  });

  it("extra fields (timestamp) don't break mobile parsing", () => {
    const payload = createPairingPayload(
      testDeviceId,
      testPublicKey,
      testEncryptionPublicKey,
      testRelayUrl,
      testDeviceName
    );

    // payload includes `timestamp` (a number) which isn't required by mobile
    expect(payload).toHaveProperty("timestamp");
    expect(typeof payload.timestamp).toBe("number");

    const qrData = { ...payload, pairingId: testPairingId };
    const serialized = JSON.stringify(qrData);

    // Mobile should still parse successfully (forward-compat)
    const parsed = mobileParseQRData(serialized);
    expect(parsed).not.toBeNull();
  });

  it("missing pairingId causes mobile parse to fail", () => {
    const payload = createPairingPayload(
      testDeviceId,
      testPublicKey,
      testEncryptionPublicKey,
      testRelayUrl,
      testDeviceName
    );

    // Oops — forgot to add pairingId (no spread)
    const serialized = JSON.stringify(payload);
    const parsed = mobileParseQRData(serialized);
    expect(parsed).toBeNull();
  });

  it("missing deviceName causes mobile parse to fail", () => {
    const payload = createPairingPayload(
      testDeviceId,
      testPublicKey,
      testEncryptionPublicKey,
      testRelayUrl,
      testDeviceName
    );
    const qrData = { ...payload, pairingId: testPairingId };

    // Remove deviceName
    const modified = { ...qrData } as Record<string, unknown>;
    delete modified.deviceName;
    const serialized = JSON.stringify(modified);

    const parsed = mobileParseQRData(serialized);
    expect(parsed).toBeNull();
  });

  it("missing encryptionPublicKey causes mobile parse to fail", () => {
    const payload = createPairingPayload(
      testDeviceId,
      testPublicKey,
      testEncryptionPublicKey,
      testRelayUrl,
      testDeviceName
    );
    const qrData = { ...payload, pairingId: testPairingId };

    const modified = { ...qrData } as Record<string, unknown>;
    delete modified.encryptionPublicKey;
    const serialized = JSON.stringify(modified);

    const parsed = mobileParseQRData(serialized);
    expect(parsed).toBeNull();
  });

  it("non-string field values cause mobile parse to fail", () => {
    const payload = createPairingPayload(
      testDeviceId,
      testPublicKey,
      testEncryptionPublicKey,
      testRelayUrl,
      testDeviceName
    );
    const qrData = { ...payload, pairingId: testPairingId };

    // Set deviceId to a number instead of string
    const modified = { ...qrData, deviceId: 12345 };
    const serialized = JSON.stringify(modified);

    const parsed = mobileParseQRData(serialized);
    expect(parsed).toBeNull();
  });

  it("field values are preserved exactly (no trimming/transformation)", () => {
    const weirdDeviceName = "  My Device With Spaces  ";
    const payload = createPairingPayload(
      testDeviceId,
      testPublicKey,
      testEncryptionPublicKey,
      testRelayUrl,
      weirdDeviceName
    );
    const qrData = { ...payload, pairingId: testPairingId };
    const serialized = JSON.stringify(qrData);

    const parsed = mobileParseQRData(serialized);
    expect(parsed).not.toBeNull();
    expect(parsed!.deviceName).toBe(weirdDeviceName);
  });
});
